### ISSUE TITLE
npm install fails with: Invalid package name "#crypto": name can only contain URL-friendly characters

### ISSUE THREAD

**Issue by ideadapt** [gr2m/universal-github-app-jwt#106] opened 2024-09-22 19:03 UTC
I try to deploy my app with deno on deno.dev. The app uses @octokit/auth-app > universal-github-app-jwt@v2.2.0. The package.json of universal-github-app-jwt contains #crypto in import directive: https://github.com/gr2m/universal-github-app-jwt/blob/e3e1a338ea5ee1271fe279742783b6d87b74b57c/package.json#L7

The error is: 
```
[Package Error] "universal-github-app-jwt@v2.2.0" could not be built. (Imported by "@octokit/auth-app").
[1/5] Verifying package is valid…
[2/5] Installing dependencies from npm…
[3/5] Building package using esinstall…
Running esinstall...
Invalid package name "#crypto": name can only contain URL-friendly characters
```

I am not really sure if this is an npm issue, or esinstall, or universal-github-app-jwt. The node version used is at least 19. Running a fresh npm install locally with version 20 does not have this issue. Do you have any idea what the issue is here?

**Comment by gr2m** [comment] 2024-09-22 19:44
I tried to install the package in Node v18.20.4 and v19.9.0, I was not able to reproduce the error. Node 19 is no longer supported by the way, you shouldn't use it.

I'm not sure what `esinstall` is, but my guess is that's the problem. I'll close the issue as there is nothing actionable for me to do here, but please keep commenting if you find a way for me to reproduce the problem. The syntax itself (`#crypto`) is supported by all currently supported node and npm versions, and you are the first I can recall who ran into this particular problem. That all points to the cause of it being somewhere else.

**Closed by gr2m** 2024-09-22 19:44 UTC
